### ISSUE TITLE
Hope you can add Ninja's description at UBP!

### ISSUE THREAD

**Issue by mthli** [balzathor/UltimateBrowserProject#1]
Today I know that there is a browser in XDA called [UltimateBrowserProject](http://forum.xda-developers.com/android/apps-games/app-ultimatebrowserproject-t3130925/post61246719), which is **similar** to my product, [Ninja web browser](https://github.com/mthli/Ninja).

Since Ninja is open source so forks my code is OK, but **replace my license description** is very very **UNFRIENDLY**!

PLEASE ADD Ninja AT UBP'S LICENSE DESCRIPTION!

BTW, Ninja use [Apache License, Version 2.0](https://en.wikipedia.org/wiki/Apache_License)

**Comment by mthli** [comment]
FUCK YOU I U DON'T ADD LICENSE FOR NINJA!

**Comment by balzathor** [comment]
Sorry, forgot to add your license.
I've added many features for myself, changed many libraries too. This change should not be a problem.
Please don't be rude. Thanks.

Sorry again.

**Comment by Thunderbottom** [comment]
Added License.
