### ISSUE TITLE
Issue again

### ISSUE THREAD

**Issue by mthli** [balzathor/UltimateBrowserProject#2]
I hope the description should be added in you new version app in `Setting/Others/License`.

And the description format should be just like the `Lightning Browser` and others:

![1](https://cloud.githubusercontent.com/assets/4550173/8183679/424dbde8-1429-11e5-89cf-750cb6082a0f.png)

That's should be OK :)

**Comment by Thunderbottom** [comment]
Fine, will add in the new build :)
