### ISSUE TITLE
Add option to open link in Foreground.

### ISSUE THREAD

**Issue by Thunderbottom** [balzathor/UltimateBrowserProject#31]
Yeah some people like to open links in foreground rather than the background, so this would be fine. Will be added soon when I understand how to fix that without changing major part of the code.

**Comment by takahirom** [comment]
Does this mean to open file when finished download file?

**Comment by Thunderbottom** [comment]
No, like when you click on any link, it opens in the background. I want user to have option to open in the foreground or in the background. I'm also thinking about adding a facebook-style chat bubble to open links but im unsure on how to do so.....

**Comment by takahirom** [comment]
I think it is difficult. but there is open source library.
https://github.com/txusballesteros/bubbles-for-android

You can also use Snackbar in Design Support Library.
https://medium.com/ribot-labs/exploring-the-new-android-design-support-library-b7cda56d2c32

**Comment by Thunderbottom** [comment]
Yes I've seen it but I couldn't implement it. For now this will be abandoned, until a certain easier fix is found, can you help me [here](https://github.com/balzathor/UltimateBrowserProject/issues/32)

**Comment by takahirom** [comment]
Sorry, I don't have good solution for that issue :(

**Comment by Thunderbottom** [comment]
alright thanks for the help though :) :+1:
