### ISSUE TITLE
Allow user to select Download Location

### ISSUE THREAD

**Issue by Thunderbottom** [balzathor/UltimateBrowserProject#32]
Currently, the file is stored in the `Downloads` folder, but I'd love to have users to select the download folder.

**Comment by Thunderbottom** [comment]
So I suppose this won't be possible, as for now, I'll be closing this, if anyone has any idea on how to deal with this, I'm down for it.

**Comment by james9909** [comment]
You can change the download destination so just have the user fill out a field in the settings

**Comment by Thunderbottom** [comment]
No, it should be like when download begins, the user should be asked where the file needs to ne saved.
