### ISSUE TITLE
Empty space created when hiding bottom omnibox

### ISSUE THREAD

**Issue by james9909** [balzathor/UltimateBrowserProject#35]
Upon hiding the omnibox at the bottom position, empty space at the top is created, which does not occur when hiding the omnibox at the top position. It is not an animation problem, since I tried hiding both using the same method, <code>omnibox.setVisibility(View.GONE)</code> without any animations. I am unsure as to how to solve this, so if anyone has any ideas, that would be great. The code can be found over at the <code>feature-fullscreen</code> branch.

**Comment by Thunderbottom** [comment]
Maybe @takahirom  can help. Also, you can try setting the webView to fit the page size.

**Comment by takahirom** [comment]
I’ll give it a try.

**Comment by takahirom** [comment]
Margin might be the cause of the problem.
https://github.com/balzathor/UltimateBrowserProject/blob/feature-fullscreen/app/src/main/res/layout/main_bottom.xml#L91-91

**Comment by Thunderbottom** [comment]
I think so that should be the problem too...

**Comment by james9909** [comment]
So can I just remove the padding entirely?

**Comment by Thunderbottom** [comment]
You can try to, or set the padding to 0 when you enable fullscreen mode at the bottom.

**Comment by takahirom** [comment]
I think so too.

**Comment by Thunderbottom** [comment]
That padding was supposed to keep the application webView inside the screen, as the omnibox size is 48dp.

**Comment by james9909** [comment]
Thanks for the help guys!

**Comment by takahirom** [comment]
:+1:

**Comment by Thunderbottom** [comment]
Nice :)

**Comment by Thunderbottom** [comment]
So is it fully functional now? You can merge it with the main repo then :)

**Comment by james9909** [comment]
I'm testing it a bit more, but I will later

**Comment by Thunderbottom** [comment]
Alright :) take your time

**Comment by Thunderbottom** [comment]
Tested it, animations still require a bit of tweaking. When the omnibox hides, there's a second of gap between the omnibox hiding where the background color is shown.

**Comment by james9909** [comment]
Fixed for the omnibox at the top, but not the bottom

**Comment by Thunderbottom** [comment]
Is there any problem?

**Comment by james9909** [comment]
Basically what I did is put the omnibox in the content frame and bring it to the front, but if I do that for the bottom one, the omnibox is brought to the top of the screen.

**Comment by Thunderbottom** [comment]
Can't you do something like chrome where the searchbar moves along with the page scroll speed?

**Comment by james9909** [comment]
I can try

**Comment by james9909** [comment]
So its called QuickReturn but I'm not sure how to implement it

**Comment by Thunderbottom** [comment]
I'll take a look at it although I'm sure i won't know how to do it either

**Comment by Thunderbottom** [comment]
Or you can try something like [this](http://stackoverflow.com/questions/27163374/hide-only-the-action-bar-on-scroll-not-action-bar-tabs)

**Comment by Thunderbottom** [comment]
[There are quite a few libraries and examples too, now](https://github.com/search?utf8=✓&q=quick+return)

**Comment by james9909** [comment]
I'm still a little confused, so if you want to do it, go ahead

**Comment by takahirom** [comment]
The ObservableScrollView also might be good to look at.
But, I don't know how to adapt to WebView.
https://github.com/ksoichiro/Android-ObservableScrollView

**Comment by Thunderbottom** [comment]
I'm more confused than you are, I will try it though :)

**Comment by Thunderbottom** [comment]
[This](https://github.com/ksoichiro/Android-ObservableScrollView/blob/master/samples/src/main/java/com/github/ksoichiro/android/observablescrollview/samples/ViewPagerTabScrollViewActivity.java) might be it what you're looking for.

**Comment by Thunderbottom** [comment]
[This](https://github.com/ksoichiro/Android-ObservableScrollView/tree/master/samples/src/main/java/com/github/ksoichiro/android/observablescrollview/samples) Looks easy, I agree with @takahirom , I don't know how to implement it :laughing:
