### ISSUE TITLE
Add Deep-Link Support

### ISSUE THREAD

**Issue by Thunderbottom** [balzathor/UltimateBrowserProject#36]
Allow Application to ask user to choose whether to open webpage or the application.
For example when you click on Twitter link, it should ask user whether the user wants to open the Twitter app or go to the webpage.

**Comment by Thunderbottom** [comment]
@takahirom any help on this would be appreciated, I don't know what to do, but this feature is what causing people to not use this browser. It is a basic feature, but is very very useful.

**Comment by takahirom** [comment]
Probably.. You can try this in shouldOverrideUrlLoading
https://github.com/android/platform_packages_apps_browser/blob/41c050d8ff87c95377a80646b6e6683983be8ab7/src/com/android/browser/UrlHandler.java#L118

**Comment by Thunderbottom** [comment]
Can you help me add it, the only thing I understood is that we need to resolve the intent, and then check whether the application is available and then launch it. But i don't know how that would work....

**Comment by takahirom** [comment]
OK.
Because busy with work and study, it might be a little late.

Sorry for my bad English.
I want to study English.
If you do know the English, please tell me if there is a place where I am wrong...

**Comment by Thunderbottom** [comment]
Yeah, I will help you learn English :) and its alright, take your own time, I release every new version once in 10-12 days.

Because `I'm (or I am)` busy with work and study.

**Comment by takahirom** [comment]
Thanks!

**Comment by Thunderbottom** [comment]
Works just as intended :D Thanks @takahirom
