### ISSUE TITLE
I Love how kids say everything is their own project!

### ISSUE THREAD

**Issue by Thunderbottom** [balzathor/UltimateBrowserProject#45]
Here's a rip-off of UBP.
This guy here claims that both the devs were "affiliated" and says both the projects are now different. I don't actually care about that much, all I do care about is that, he has removed the license from the settings. Also, where as GPL3 claims that the other "developer" has to retain a license and make it closed-source only with the devs permission, while still claiming the license. The license though, is no where to be found in the application.

You can check out the applications -
[Snap Browser Lite](https://play.google.com/store/apps/details?id=io.snapbrowser.lite)
[Snap Browser Pro](https://play.google.com/store/apps/details?id=io.snapbrowser.pro)

And report it needfully.

**Comment by Thunderbottom** [comment]
Never mind he's asked me about it now. And we're fine with it, totally.

**Comment by Thunderbottom** [comment]
Not really closed, cause fuck that guy.

**Comment by james9909** [comment]
When are we going to release on the play store?

**Comment by Thunderbottom** [comment]
When it's completely stable, and I have money to open a developer account. As a student I'm totally broke.

**Comment by Thunderbottom** [comment]
@james9909 can you fix the bottom omnibox scrolling, just don't make it scroll as it happens for top. People who want the omnibox to scroll will switch to top view. Bottom will remain intact.

**Comment by davimount** [comment]
This guy?
https://github.com/LorenzoZanotto
https://www.materialup.com/posts/snap-browser

**Comment by james9909** [comment]
I'm away right now but I'll try to get it done as soon as possible.

**Comment by Thunderbottom** [comment]
@davimount  yep that fkin guy, he's that one guy who ripped off Cyanogenmods Apollo under his name lol

**Comment by takahirom** [comment]
If you want to release on play store, I suggest to disable background playing of youtube.
https://github.com/mthli/Ninja#why-not-google-play

**Comment by Thunderbottom** [comment]
Yeah, will do that, release will take a lot of time though!

**Comment by xdevs23** [comment]
I saw that browser too, I think taking the work from others, saying it is the own work and selling it is not good.

...**Reported on Google Play**

**Comment by Thunderbottom** [comment]
LOL I did that a long time ago, no reply from Google.

**Comment by xdevs23** [comment]
Let's see if it works...
