### ISSUE TITLE
New theme Incomplete

### ISSUE THREAD

**Issue by Thunderbottom** [balzathor/UltimateBrowserProject#48]
@james9909 When are you completing the new theme?
I suppose it's still pending [here](https://github.com/balzathor/UltimateBrowserProject/commit/1ef36a382182949322f8c856ead914fd5644161f)

**Comment by james9909** [comment]
Yes, currently some items, like the dialogs, still need to have a dark version, but I'm not going to finish it soon because I'm on vacation.

**Comment by Thunderbottom** [comment]
Alright, I'll wait for you to finish that and then we'll add it to the new version

**Comment by Thunderbottom** [comment]
I've fixed some bugs and now you can print through the app itself. So I'll wait until you are do so we can release this new one

**Comment by Thunderbottom** [comment]
@james9909 can you finish the theme please, I'll land a new update soon before I'm done with this for a while?

**Comment by james9909** [comment]
Okay, I'll finish it this weekend.

**Comment by Thunderbottom** [comment]
Alright thanks :)

**Comment by james9909** [comment]
Can you check out the theme so far? I have pretty much everything covered, but I'm not sure what else you would like to be darkened. Additionally, instead of using an overflow menu in ClearActivity, couldn't we use the original 'done all' icon?

**Comment by Thunderbottom** [comment]
Yeah sure, will check it out real quick

**Comment by Thunderbottom** [comment]
Also, if I have mistaken some icon for something else, you can change it! :D

**Comment by Thunderbottom** [comment]
The themes don't work, its still light

**Comment by james9909** [comment]
Did you launch the project from the feature-themes branch? It works for me.

**Comment by Thunderbottom** [comment]
yes I did, can you post some screens?

**Comment by james9909** [comment]
Actually it might be because I only set the themes for lollipop or higher. I'll work on the themes for lower versions.

**Comment by james9909** [comment]
I tested the dark theme on an emulator, so some things may not be perfect. Also, if you feel that any of the colors are off, feel free to change them to whatever.

**Comment by Thunderbottom** [comment]
Yeah i ran them on Bluestacks for test, the only page that was dark was the Readability menu

**Comment by Thunderbottom** [comment]
The colors are just fine, no need to change them

**Comment by james9909** [comment]
Were the settings dark? I tried on a 4.4.4 emulator and it looked fine.

**Comment by Thunderbottom** [comment]
No, can you post some screenshots?

**Comment by Thunderbottom** [comment]
Alright you posted a newer version, let me check that out
