### ISSUE TITLE
Enter key in address bar not working

### ISSUE THREAD

**Issue by jaggs6** [balzathor/UltimateBrowserProject#6]
I was trying to test your app on Genymotion emulator. but couldn't open any webpage as a physical keyboard is attached. I am not able to press enter after typing a address in the address bar. the soft keyboard is not shown when physical keyboard is attached. I am sure this issue will also happen on devices with external keyboards attached.

**Comment by Thunderbottom** [comment]
This is currently under development.

**Comment by Thunderbottom** [comment]
I think it'll be fixed in the new release. Tried doing it. You can check the sources and see if I have had some fault in making it work.

**Comment by jaggs6** [comment]
Sweet thanks. Do you have a trello board? I would like to contribute.

**Comment by Thunderbottom** [comment]
I do have a Trello board but I haven't added anything to it yet. Like its all blank as for now.
I will do it tomorrow during the day time and then let you know about it. I'm keen on working on Trello.

Regards.

**Comment by jaggs6** [comment]
If you don't want a trello board u can even advertise features u need in
Github Issues with Help Wanted labels.

**Comment by Thunderbottom** [comment]
Well I would love to have trello board :)
