### ISSUE TITLE
Fix 'Screenshot' on Android 5.0+

### ISSUE THREAD

**Issue by Thunderbottom** [balzathor/UltimateBrowserProject#63]
I'll do this when I get time, just adding here so that I remember it when I'm free.

**Comment by xdevs23** [comment]
Webpage to PDF... sounds cool.
Why not use a PHP server-side script for doing this? :D
Or are you planing this?

**Comment by Thunderbottom** [comment]
Uh I suppose [this](http://www.htm2pdf.co.uk/html-to-pdf-api/) might work.

**Comment by Thunderbottom** [comment]
Can you try it out?

**Comment by xdevs23** [comment]
I think wkhtmltopdf.org is better... But I will try it in next days

**Comment by xdevs23** [comment]
But I will try whats possible

**Comment by xdevs23** [comment]
#69

**Comment by xdevs23** [comment]
The problem is in BrowserUnit.screenshot()....
On Android 5.0+ there's a EACCES error (Permission denied) to path /sdcard/Pictures/....png
If you search on Google, you see that you don't have permissions on sd card (or "internal storage" /sdcard, known as ExternalStorage) anymore.

Either we need to use a shell for writing to file or use root permissions.

That would be the last solution if we don't find any.

**Comment by Thunderbottom** [comment]
Or we can just write in the internal directory

**Comment by Thunderbottom** [comment]
[Check this out](http://stackoverflow.com/a/26765884)

**Comment by Thunderbottom** [comment]
Can you do it please if it is not a problem? I have finals tomorrow which I need to study for.

**Comment by xdevs23** [comment]
I tried it but I don't know how to fix it

**Comment by takahirom** [comment]
How about this?

``` java
        File dir;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            dir = context.getExternalMediaDirs()[0];
        } else {
            dir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES);
        }
```

**Comment by xdevs23** [comment]
Will test it out, anyways thank you for that wonderful piece of code 😀👍

**Comment by takahirom** [comment]
Thanks! :)

But, I have no confidence.
Please test!

I tested it in Genymotion Android 5.1.
It returns path `/storage/emulated/0/Android/media/io.github.UltimateBrowserProject/Google.3.png`.
The image can be seen in the gallery app.

**Comment by xdevs23** [comment]
Oh I didn't know that it appears in gallery... I also use genymotion, I will see, but I'd rather like to store it in a path like /sdcard/Pictures or /sdcard/UBPScreenshots..... But I will use your code before anything else.

**Comment by xdevs23** [comment]
Works!
