### ISSUE TITLE
TO DO

### ISSUE THREAD

**Issue by xdevs23** [balzathor/UltimateBrowserProject#69]
Here is everything what needs to be done and what has been recently finished.

Use following formatting:

``` plaintext
 - [ ] something to do
 - [x] something finished
```

Just edit this comment and change the content below:

<hr>

**TO DO:**

To fix:
- [ ] Switching tabs
- [ ] Fix something in `ActivityThread.performResumeActivity()`

To do:
- [x] Native updater
- [ ] Select DL Location
- [ ] Change font size

Code status: Waiting for native updater to be completed and bugs to be fixed

**Comment by xdevs23** [comment]
- [ ] Optimize / animate omnibox
From [ThunderBottom issue #68](https://github.com/Thunderbottom/UltimateBrowserProject/issues/68):
 - [ ] Select DL Location
 - [ ] Change font size

**Comment by Recol** [comment]
I also prefer the second, however the "todo" should be changed to "to do".

**Comment by xdevs23** [comment]
Done

**Comment by Thunderbottom** [comment]
Gonna add more when I find more.

**Comment by xdevs23** [comment]
Yep

**Comment by xdevs23** [comment]
Added issue

**Comment by xdevs23** [comment]
**Many things fixed and improved**

**Comment by Thunderbottom** [comment]
Are we ready to release a beta?

**Comment by xdevs23** [comment]
A beta, of course.

**Comment by Thunderbottom** [comment]
Website in Fullscreen mode still shows `about:blank` at the bottom while scrolling

**Comment by xdevs23** [comment]
Oh did not test full screen mode. Will fix it.

**Comment by Thunderbottom** [comment]
4 more days and I'm done with finals :)

**Comment by xdevs23** [comment]
Cool, in the next week, beginning on wednesday, I have holidays. Much more time for coding.

**Comment by Thunderbottom** [comment]
Well so we can be sure that one version will be released in about a week from now, maybe even earlier!

**Comment by xdevs23** [comment]
Yes, I think so.

**Comment by xdevs23** [comment]
@Thunderbottom beta can be released now, can't it?

**Comment by Thunderbottom** [comment]
I'm sick I'll check later tomorrow. Good job, though :)

**Comment by xdevs23** [comment]
Yep, thanks.

**Comment by Thunderbottom** [comment]
Alright so I got someone to test it and they sent me this -
![screenshot_2015-12-23-14-20-37](https://cloud.githubusercontent.com/assets/11243138/11973500/e4ecc2be-a980-11e5-9d46-abfa5c8effa8.png)

Plus the app force closes like "Unfortunately UBP has stopped" when you press the minimize button, have you messed with the onPause method?

**Comment by Thunderbottom** [comment]
Stack Trace for some help :

```
Fatal Exception: java.lang.RuntimeException: Unable to start service io.github.UltimateBrowserProject.Service.HolderService@ea08a7e with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String io.github.UltimateBrowserProject.b.a.b()' on a null object reference
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3071)
       at android.app.ActivityThread.-wrap17(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5466)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String io.github.UltimateBrowserProject.b.a.b()' on a null object reference
       at io.github.UltimateBrowserProject.Service.HolderService.onStartCommand(Unknown Source)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3054)
       at android.app.ActivityThread.-wrap17(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5466)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
```

**Comment by Thunderbottom** [comment]
Also, I've invited you to our crashlytics page, check your mail.

**Comment by Thunderbottom** [comment]
Removed "Clear cache when app starts up" cause it's pretty much unwanted.

**Comment by Thunderbottom** [comment]
Ok, so the app crash no longer occurs, guess I want a commit behind on my PC. But the floating omnibox is still there, and it happens while typing.

**Comment by xdevs23** [comment]
Well, I didn't get any crashes in the latest commit.

Your crash came from HolderService.onStartCommand

**Comment by Thunderbottom** [comment]
Yes, it's not happening now. But the bottom omnibox bug still persists.

**Comment by xdevs23** [comment]
I think that is device-dependent.

On my device it doesn't happen at all, in genymotion only when the keyboard is showed.

**Comment by xdevs23** [comment]
I will try to make it device-independent

**Comment by xdevs23** [comment]
And please don't minify the application if you want to debug it and only build in debug mode so in the stack trace is the exact line of code where the exception happened.

**Comment by xdevs23** [comment]
@Thunderbottom are we going to release a **beta** or a new **stable version**?
Let me know, because we need to change `AppConfig.java` if it is stable version.

**Comment by Thunderbottom** [comment]
Beta probably, we'll stick to beta forever until I become better at this. :)

**Comment by Thunderbottom** [comment]
This thing is for learning only, the main stuff is coming when I'm done learning

**Comment by xdevs23** [comment]
Allright. I also am still learning. :D

Would you like a good updater?

I already have made two of them for me, and if you want, I can integrate it into UBP.

Checking for updates, downloading them and installing is all done automatically.

If the device is rooted, it can install directly without user interaction, if not, the user will be prompted in the package installer to update the application.

Sounds cool, what?

**Comment by xdevs23** [comment]
But let us first release our new beta :D

**Comment by Thunderbottom** [comment]
Damn that's cool, I'd like to check the source do you have it on your Git?

**Comment by Thunderbottom** [comment]
I did one that would check for updates and notify, but that's all that it would do. I linked directly to the apk so it downloaded the update apk and let users install it manually.

**Comment by Thunderbottom** [comment]
Your updater might be useful for weekly updates that I'm planning to do from January

**Comment by xdevs23** [comment]
No, I don't have published the source.

But I can start implementing it after you released the beta.

**Comment by xdevs23** [comment]
Did you test the build already?

**Comment by Thunderbottom** [comment]
I'm doing it right now

**Comment by xdevs23** [comment]
Ok, tell me how it goes then.

**Comment by Thunderbottom** [comment]
Sure, I'm out tomorrow but expect the version to be out by this time, tomorrow. Good job.

**Comment by xdevs23** [comment]
Allright, thank you.

**Comment by xdevs23** [comment]
@Thunderbottom I am being spammed by Crashlytics with issues 😂😂

**Comment by Thunderbottom** [comment]
Oh just disable the email notifications.

**Comment by Thunderbottom** [comment]
You still haven't accepted the invitation according to crashlytics...

**Comment by xdevs23** [comment]
I think I did accept it....

**Comment by Thunderbottom** [comment]
I made you the admin right now

**Comment by xdevs23** [comment]
Lol I cannot login into my fabric account anymore 😂

**Comment by xdevs23** [comment]
It says wrong email or password but I am sure that I entered the correct one... Let me reset it...

**Comment by xdevs23** [comment]
Well, i need to wait 45 minutes now before my account is unlocked

**Comment by Thunderbottom** [comment]
LMAO.

**Comment by xdevs23** [comment]
Now it works 😂

**Comment by xdevs23** [comment]
Our stats are **booming**
![image](https://cloud.githubusercontent.com/assets/6959245/11993777/4184b496-aa35-11e5-8fb6-29adf9d5613b.png)

**Comment by Thunderbottom** [comment]
yeah they do when a new version comes out, I once hit 33k new users per month and 12.7k active sessions for 2-3 weeks when I released v.1.4.6.

**Comment by Thunderbottom** [comment]
People on XDA are complaining that tab switcher cannot switch tabs...

**Comment by Thunderbottom** [comment]
They're using volume keys to switch tabs

**Comment by Thunderbottom** [comment]
I think it is device dependent cause it is working for me on some devices and not on others..

**Comment by xdevs23** [comment]
Yes I think it is device-dependent...

**Comment by Thunderbottom** [comment]
Do you have a quick fix for it? We'll release a incremental update soon then, maybe.

**Comment by xdevs23** [comment]
I am currently working on the updater.

**Comment by Thunderbottom** [comment]
Like I've been planning weekly updates starting next year, which, hopefully, I'll start supplying on a weekly/bi-weekly basis

**Comment by Thunderbottom** [comment]
Well can you not do both by tomorrow? I mean it is hard but should be possible right? If you're enjoying with family, you can take your time because this is the time to enjoy imo :)

**Comment by Thunderbottom** [comment]
I'll also start the PDF thing soon so we should be at least stable till next year and we haven't updated for a long time so..

**Comment by xdevs23** [comment]
I will try to fix it as soon as possible.

**Comment by xdevs23** [comment]
I hope you know what I mean with "native".

The updater was a webview which loaded a webpage, and when you click on update, it downloads it and installs it.

Making it native is just removing the webview, creating a layout and doing everything in java.

**Comment by Thunderbottom** [comment]
Yeah I know what native is...

**Comment by xdevs23** [comment]
Yep.. Just to be sure, because I don't want that you think I am going to use native libraries (C++)

**Comment by Thunderbottom** [comment]
Of course you aren't going to do that.. duh.

**Comment by xdevs23** [comment]
Updater is finished

**Comment by Thunderbottom** [comment]
Cool, so we ready to host an incremental?

**Comment by Thunderbottom** [comment]
I'll do it tomorrow, will test this one thoroughly and post the update

**Comment by Thunderbottom** [comment]
So we'll know the bugs beforehand and I'll start working :) FINALLY!

**Comment by xdevs23** [comment]
Some bugs are still there but some were already fixed after 2.0.

I think you can release an update.

**Comment by Thunderbottom** [comment]
Alright, testing now, will post an update tomorrow! have a good evening :)

**Comment by xdevs23** [comment]
Thanks, a good evening for u too!

**Comment by xdevs23** [comment]
Btw, as you can see, I added some cool features, such as `DownloadUtils.downloadString(url)`. With this function you can download text files and save them into a String, without saving it onto the storage.

**Comment by xdevs23** [comment]
Can you please take a look into my new project [Cornowser](http://github.com/xdevs23/Cornowser)
It is a web browser based on Crosswalk (Chromium)

**Comment by Thunderbottom** [comment]
Hey @xdevs23 I'll check that later, I'm pretty busy with stuff right now, but I took a quick look at it and it  seems pretty good.

@takahirom Is there any way that we can implement [this](http://suggestqueries.google.com/complete/search?output=toolbar&hl=en&q=theory) from [here](http://stackoverflow.com/questions/5102878/google-suggest-api) into our search bar? Like it should show some search suggestions in the omnibox.

**Comment by xdevs23** [comment]
Allright. Do you want to join the project? I have a good idea: we could share code across both projects. So, we can implenent good code from my project into yours and good code from yours into mine.

**Comment by Thunderbottom** [comment]
Sure!

**Comment by xdevs23** [comment]
Great

**Comment by xdevs23** [comment]
I used following regex patterns for detecting of address format:

``` java
    public static Pattern urlRegEx = Pattern.compile(
            "(" +
                    "(^(https|http|ftp|file|rtmp)://.*[.].*)|" +    // Protocols for adresses
                    "(javascript:).*" +                             // Javascript

                    ")"
    );

    public static Pattern urlSecRegEx = Pattern.compile(
            "(" +
                    "(.*[.].*)|" +                                  // Adresses without protocol
                    "(localhost).*|" +                              // localhost
                    "(.*[.].*[.].*[.].*)|" +                        // IPv4 adresses
                    "(.*(::|:).*)|" +                               // IPv6 adresses
                    "(.*@.*[.].*)" +                                // user@host.domain

                    ")"
    );
```

And it works perfectly fine. If it doesn't match it just searches the entered text on google.

And this is what I used for handling it:

``` java
    @Override
    public void load(String url, String content) {
        Matcher urlRegExMatcher     = CornResourceClient.urlRegEx   .matcher(url);
        Matcher urlSecRegExMatcher  = CornResourceClient.urlSecRegEx.matcher(url);
        String nUrl = url;
        if(urlRegExMatcher.matches()) nUrl = url;
        else if(urlSecRegExMatcher.matches()) nUrl = "http://" + url;
        else nUrl = "https://google.com/search?q=" + url.replace(" ", "+");
        super.load(nUrl, content);
    }
```

**Comment by Thunderbottom** [comment]
Oh, we have this in here, don't we?

**Comment by xdevs23** [comment]
We already have a regex pattern. I am going to improve it a bit. I think it is no difference between the result of mine and yours, you can decide which you take.

**Comment by xdevs23** [comment]
``` java
String regex = "^((ftp|http|https|intent)?://)"                      // support scheme (how about javascript:?)
                + "?(([0-9a-z_!~*'().&=+$%-]+: )?[0-9a-z_!~*'().&=+$%-]+@)?" // ftp.user@
                + "(([0-9]{1,3}\\.){3}[0-9]{1,3}"                            // IP -> 199.194.52.184
                + "|"                                                        // IP DOMAIN
                + "([0-9a-z_!~*'()-]+\\.)*"                                  // -> www.
                + "([0-9a-z][0-9a-z-]{0,61})?[0-9a-z]\\."                    //
                + "[a-z]{2,6})"                                              // first level domain -> .com or .museum
                + "(:[0-9]{1,4})?"                                           // Port -> :80
                + "((/?)|"                                                   // a slash isn't required if there is no file name
                + "(/[0-9a-z_!~*'().;?:@&=+$,%#-]+)+/?)$";
```

That is ours. But it is long and confusing.

**Comment by Thunderbottom** [comment]
Yea our's won't work...

**Comment by Thunderbottom** [comment]
And yeah we have also broken "Open links in the background" while you changed all those views so you'll have to fix that too...

**Comment by xdevs23** [comment]
Yep... I have seen that this browser is a derivate of Ninja browser... Is that why you can't fix the bugs?
I have to say that the views etc. were really messed up, that's why I had to change everything.

**Comment by Thunderbottom** [comment]
No, I can fix bugs but I have too little time with all the work I've got, this was just a fun project.

**Comment by Thunderbottom** [comment]
You can have it all if you want now, I have little to no time to continue this, maybe next year I can work on this again...

**Comment by xdevs23** [comment]
Allright. I will take a look later. I want to get my browser to a stable state and release the first version, maybe until next year. Yes, that is possible. Somehow I do those things really fast, while others need a much longer time to do it.

**Comment by Thunderbottom** [comment]
I have a big list of features that many people want in a browser, do you want it? I can get it to you in maybe a day or two, and those are like the "most wanted" features in a browser. Also, you can take a look at [Snapdragon Browser](http://www.xda-developers.com/chromium-optimized-for-snapdragon-devices/), If you can implement most of these stuff, then mark my words you'll have the best browser. 

**P.S.** You can make some features as "Plugins" so that people get only what they want and no bloats, I'd have done this if I had time, and I started this shit thinking I'd have a lot of time to work on it, but oh boy, was I wrong... Also, from my experience, just do one thing at a time, as they say "Take what you have in your hand and use it, don't stretch out for something more, as the one thing you have in your hand will be lost", Good luck.

**Comment by Thunderbottom** [comment]
And I may wrap this stuff up soon, do you want me to have people check out your browser? cause your stuff sounds promising and you have good skills too..

**Comment by xdevs23** [comment]
Well, as you might know, browsers which just use the webview could be dangerous because on older android versions the webview engines are outdated and on 4.3 and lower you have a very awful performance. It's a good idea to create a such lightweight browser, if you just want to save free space and have a good browsing experience though. I think you should let your project continue existing but only work on it until it is stable enough. Then we could work on Cornowser and make a better browsing experience... What do you think? I also will try including native ARM64 support to have best performance on new 64bit devices. 
And you need to know that I learned programming by watching youtube videos, searching for code examples in the net and trying out things myself.
I am just 15 years old and do programming only as "spare time activity".

Anyways, how about my idea?

**Comment by xdevs23** [comment]
First I have only programmed in Visual Basic, later I started learning HTML, CSS and JavaScript, I also have made my project in C++, and I started programming in Java. I made minecraft plugins and then started making android apps.

Now I can write code in Java, VB.Net, C++, HTML, CSS, SCSS, JavaScript, PHP and bash shell scripting.

**Comment by xdevs23** [comment]
Here is some work in Visual Basic: https://github.com/xdevs23/xD

**Comment by Thunderbottom** [comment]
Yeah we can work on your idea, I'll just let 1.4.6. be the last version and from sometime around next year, I'll start helping you out. I still need to learn a lot, where _specifically_ did you learn Android coding from? Cause I just did Java and read some documentations and then started to work on stuff. It was hard but now I have a good hold of it, although I'll need some Android specific videos to be good to go.

**Comment by xdevs23** [comment]
I started watching YouTube videos about basic java programming, later I wanted to create my own java console program, which worked, and later I started watching videos about bukkit plugins.

And then I started watching a few videos about android programming. Then I just started programming and if I didn't know something or needed help I just searched on Google for solutions and used copy&paste.

With the time I learned the code and just tried things out without knowing what I am really doing and with the time I developed my programming skills and am always improving it with each line of code I write.

And I didn't buy any books etc. for learning it, I didn't participate in any course or similar, I just started doing it myself and now you can see the results.

My code might not be perfect or the best but it is not that bad and with each new line of code I improve my skills and experience.

**Comment by Thunderbottom** [comment]
Well I did the exact same thing, guess my practice just wasn't enough. Cool, now I have stuff to do in my leisure time! Thanks :)

**Comment by xdevs23** [comment]
And never forget **to not give up**
You can stop for a while if you can't solve a problem but later you might be able to solve it.

**Comment by Thunderbottom** [comment]
Well anyways, how farm along is your browser from initial release? You should totally post an XDA thread asking people what features they want because during the later time, when you have a release version, you might not want to change most of the code just to fit one feature in, so this just might be the right time to ask for features and show off your browser. I'll help you if you need.

**Comment by xdevs23** [comment]
Yes, good idea, I was already thinking about it.

And I always try to code it in a way, which lets me easily change it without messing it up completely.

I create "modules", create more tiny methods/functions and put everything together.

And I try to make it unique. So I use `RelativeLayout` for everything, which makes the work a lot easier.

However, let us post a thread on XDA.

**Comment by xdevs23** [comment]
My browser should be ready for first release within a week, but it doesn't have to.

**Comment by Thunderbottom** [comment]
Well, the most important thing is to comment some stuff which you might not remember later on, this is what I've learnt from everything I've done, and now I make sure to comment on what it does whenever I write any methods.

**Comment by Thunderbottom** [comment]
Do you have any _beta_ kinda thing ready? I can give it a go for you.

**Comment by xdevs23** [comment]
And in your code you say that the file chooser doesn't work on some android versions but on the app I made for my school colleagues the file chooser works on any android version. MinSdk is 15 and targetSdk is 23

**Comment by Thunderbottom** [comment]
It works on most devices, but on _some_ MediaTek devices, idk why it doesn't want to..

**Comment by xdevs23** [comment]
After I implemented the updater, you will be able to install latest updates.

Later I will include a possibility to choose whether it should check for beta updates or not.

**Comment by xdevs23** [comment]
I have MediaTek and it works on that app ^^

**Comment by Thunderbottom** [comment]
I'm mostly done with this for now, you can use any code you want for your browser.

**Comment by Thunderbottom** [comment]
I think you should not work on this for now... Make your browser better instead

**Comment by xdevs23** [comment]
Allright, I will add you to contributors, though

**Comment by Thunderbottom** [comment]
Also, [Reddit hates `WebView`](https://www.reddit.com/r/Android/comments/3am276/ultimate_browser_project_is_an_opensource)

**Comment by xdevs23** [comment]
Yes, that's what I said. Many browsers on Google Play are also only webviews.But in my oppinion, UBP is a great app though!

**Comment by xdevs23** [comment]
That's why I decided to use the chromium render engine

**Comment by Thunderbottom** [comment]
UBP is not that good, how I imagined it would be, but nonetheless I got to learn too much from it. Maybe my next application will be a huge success thanks to this stone :) And yea Chromium render engine is great, gives you a good HTML5 score, but an updated WebView also scores great on that regards.

**Comment by Thunderbottom** [comment]
Alright, I've closed the forum for good and added your application in the discussion, hope it'll be a good start for you :)

**Comment by xdevs23** [comment]
Thanks
