### ISSUE TITLE
[Discussion] Updater

### ISSUE THREAD

**Issue by xdevs23** [balzathor/UltimateBrowserProject#80]
We need to host some files on a web server, don't matter which one, but we need it to integrate the updater.

We could just host it on my website.

**Comment by xdevs23** [comment]
I will also create a page where you can upload a new version etc. (of course with a password which you need to tell me privately)

**Comment by Thunderbottom** [comment]
We can upload the new version to GitHub and it should work!

**Comment by xdevs23** [comment]
Yes, of course.

But we need a webserver to host a PHP file. I do this, don't worry.

**Comment by Thunderbottom** [comment]
Alright, check the other place that I commented on. People are complaining that they cannot switch the tabs

**Comment by xdevs23** [comment]
We need a static URL where the latest APK is always stored.

**Comment by Thunderbottom** [comment]
Github has static URL :dancer:

**Comment by xdevs23** [comment]
Yes, I mean something like http://github.com/.../UltimateBrowserProject.apk instead of http://github.com/.../UltimateBrowserProject.v....apk

**Comment by Thunderbottom** [comment]
Oh yeah we can do that here :D

**Comment by xdevs23** [comment]
how?

**Comment by Thunderbottom** [comment]
You're saying we need a static APK link, I've been using that since a long time so that shouldn't be a problem.

**Comment by xdevs23** [comment]
allright, I found out how it works.

**Comment by xdevs23** [comment]
Now you can release a new version :D 
Version 2.0.1, version code 2015122402
