### ISSUE TITLE
ActivityThread.java line 3092

### ISSUE THREAD

**Issue by Thunderbottom** [balzathor/UltimateBrowserProject#81]
#### in android.app.ActivityThread.performResumeActivity
- Number of crashes: 1
- Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/android-application-projects/android/apps/io.github.ultimatebrowserproject/issues/567bfb98f5d3a7f76b9e6dea](https://fabric.io/android-application-projects/android/apps/io.github.ultimatebrowserproject/issues/567bfb98f5d3a7f76b9e6dea)

**Comment by xdevs23** [comment]
This is not UBP-relevant
