### ISSUE TITLE
GLES20RecordingCanvas.java line 162

### ISSUE THREAD

**Issue by Thunderbottom** [balzathor/UltimateBrowserProject#82]
#### in android.view.GLES20RecordingCanvas.drawDisplayList
- Number of crashes: 1
- Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/android-application-projects/android/apps/io.github.ultimatebrowserproject/issues/567c052af5d3a7f76b9ea45c](https://fabric.io/android-application-projects/android/apps/io.github.ultimatebrowserproject/issues/567c052af5d3a7f76b9ea45c)

**Comment by xdevs23** [comment]
Not our fault.

**Comment by Thunderbottom** [comment]
These things will be automatically posted, if you want I can make another account just for this, so it doesn't come up under my name.

**Comment by xdevs23** [comment]
Not necessary, but some crashes are not our fault.

**Comment by Thunderbottom** [comment]
I already have made a bot.
