### ISSUE TITLE
Same Page appears with new tab as we minimize and restoring. 

### ISSUE THREAD

**Issue by nitish2429** [balzathor/UltimateBrowserProject#90]
I am Using stable version
When we perform double click on any external url:(i.e from Facebook, Whatsapp or  from any source), Pop appears with 3 option( 1. Foreground  2. Copy Link  3. Share). As we click on Foreground, page opens and when we remove this page it get removed. Just After that at same time when we minimize the app and restoring it, It appears with that page which we had removed last time after opening URL through : double click --> foreground.   

![screenshot_2016-05-20-18-11-06 1](https://cloud.githubusercontent.com/assets/17546525/15428084/0240bf2c-1eb7-11e6-9672-60a7ab11d1f8.png)
![screenshot_2016-05-20-18-11-40 1](https://cloud.githubusercontent.com/assets/17546525/15428109/24fcb2f0-1eb7-11e6-99e1-95ddeed49950.png)
![screenshot_2016-05-20-18-11-56 1](https://cloud.githubusercontent.com/assets/17546525/15428124/3004e762-1eb7-11e6-8c56-6751e6e47506.png)
![screenshot_2016-05-20-18-12-02 1](https://cloud.githubusercontent.com/assets/17546525/15428135/3ec1aace-1eb7-11e6-96b0-218b1bfa0d4f.png)

**Comment by Thunderbottom** [comment]
Will need to fix this. Thanks for reporting. Might as well answer the questions below!

> Just After that at same time when we minimize the app

So... Have you tried closing the tab or just minimized the app?

>  It appears with that page which we had removed last time after opening URL through : double click --> foreground.

So, the new page that you open, opens alongside the old page that you opened in the foreground?

**Comment by nitish2429** [comment]
i have tried by both way , after closing the tab, then after minimizing the app. In both cases it get opened with last clicked url.

If i want to open new tab by clicking '+ ' its working fine.. no problem is there. 

new tab with same page opens only after minimizing and restoring the app. This happen only if we had clicked any url from external sources. Rest all functionality is working fine !

I think it's problem from Holder activity.

**Comment by Thunderbottom** [comment]
Yes, I'll take a look at it soon, in June maybe. No time for this stuff now. Thanks for reporting though.
